gamecat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('registration/', include('django.contrib.auth.urls')),
    path('registration/', include('registration.urls')),

    path('', include('home.urls'))
]

home/urls.py
"""URL configuration for registration app"""

from django.urls import path
from . import views

app_name = 'home'   # pylint: disable=invalid-name
urlpatterns = [
    path('', views.home, name='home'),
    path('clicked', views.clicked, name='clicked'),
]

registration/urls.py
"""URL configuration for registration app"""

from django.urls import path
from django.contrib.auth import login
from . import views

app_name = 'registration'   # pylint: disable=invalid-name
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', login, name='login'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('authentication/', views.authentication, name='authentication'),
    path('authenticated/', views.authenticated, name='authenticated')
]

catalogue/models.py
from django.db import models

# Create your models here.

home/models.py
"""Model to track the number of clicks made by a user"""
from datetime import datetime
from django.conf import settings
from django.db import models

# Create your models here.
class ClicksUser(models.Model):
    """Stored data for a user who clicks"""
    clicker = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    clicks = models.PositiveBigIntegerField(default=0)
    last_click = models.DateTimeField(default=datetime.now())
    click_speed = models.FloatField(default=0)

    def __str__(self) -> str:           #pylint: disable=invalid-str-returned
        return self.clicker.username    # pylint: disable=no-member

catalogue/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
"""All views of home app"""

from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import F
from .models import ClicksUser


# Create your views here.


def home(request):
    """Display the home page"""
    user = request.user
    clicks_objects = ClicksUser.objects   #pylint: disable=no-member
    user_clicks = clicks_objects.values('clicker', 'clicks')
    # Variable information of logged in user
    username = user.username
    while True:
        try:
            # Attempt to get user click data
            user_clicks = clicks_objects.filter(clicker=user.id) #pylint: disable=no-member
            user_clicks = user_clicks.values('clicks')[0]['clicks']
            break
        # Raised if no record for user exists
        except IndexError:
            try:
                # Attempt to create record for user
                new_clicker = ClicksUser(clicker=user)
                new_clicker.save()
            # Raised if no user is logged in
            except ValueError:
                user_clicks = 0
                break
    
    # Variable containing summary information
    clicks_objects = clicks_objects.all()
    total_clicks = sum(x.clicks for x in clicks_objects)
    last_clicker = max(clicks_objects, key=lambda x: x.last_click).clicker
    average_clicks = round(sum(x.clicks for x in clicks_objects)/len(clicks_objects),1)
    most_clicker = max(clicks_objects, key=lambda x: x.clicks).clicker
    return render(request, 'home/home.html',
                  {'username': username,
                   'user_clicks': user_clicks,
                   'total_clicks': total_clicks,
                   'average_clicks': average_clicks,
                   'last_clicker': last_clicker,
                   'most_clicker': most_clicker})


def clicked(request):
    """PLACEHOLDER"""
    user = request.user
    print(user)
    clicks_objects = ClicksUser.objects.filter(clicker=user.id)   #pylint: disable=no-member
    clicks_objects.update(clicks=F('clicks') + 1)
    clicks_objects.update(last_click=datetime.now())
    return HttpResponseRedirect(reverse('home:home'))

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="eng-us">

<head>
  <title>GAMECAT</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
  <link href="{% static 'stylesheet.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="static/images/favicon.ico" >
</head>

<body>
<header>{% include "header.html" %}</header>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
<footer>{% include "footer.html" %}</footer>
</body>

</html>

templates/footer.html
<!DOCTYPE html>
<br><br><br><br><br><br>
<div id="footer_style" class="container-fluid">
  <div class="container-fluid mt-auto" style="text-align: center;">
    <div class="shadow-lg p-3 mb+5 bg-white rounded">
      <div class="row">
        <div id = "column_style" class="col-md">
          <h5>See my other things on Github!</h5>
          <a
          href="https://github.com/Kader-the-Coder/L1T24/tree/01b54797896d08957f9fa55b8a731b282231c25e"
          target="_blank">
            <img  class="icons" src="/static/images/tm_icon.png" alt="Task manager project" title="Task manager project">
          </a>
          <a
          href="https://github.com/Kader-the-Coder/L1T30/tree/57a46e89652cc38a6376024d554c8477d6a2a471"
          target="_blank">
            <img class="icons" src="/static/images/shoe_icon.png" alt="Shoe inventory project" title="Shoe inventory project">
          </a>
          <a 
          href="https://github.com/Kader-the-Coder/L2T13/tree/034110738fe37854309c82b1ef1d5b3bafa6cac6"
          target="_blank">
            <img class="icons" src="/static/images/book_icon.png" alt="Book manager project" title="Book manager project">
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

templates/header.html
<!DOCTYPE html>

<div id="header_style" class="container-fluid">
    <div class="row">
      <div class="row align-items-center" style="min-height: 5vh">
        <!--Column 1-Empty cell (Can put something here later)--------->
        <div class="col-md-2">
        </div>
        <!--Column 2-Site Logo and Name------------------------------->
        <div class="col-md-8">
            <div id="header_name" class="card-body">
              <img class="card-img-top" src="/static/images/logo.png" alt="Site logo">
              <h1 class="display-1">GAMECAT</h1>
            </div>
        </div>
        <!--Column 3-Login/Logout------------------------------------->
        <div class="col-md-2">
          {% if user.is_authenticated %}
            <!--Display when user is logged in---------------------->
            <div style="text-align: center; border-style:dashed;">
              <br>
              <h1> Logged in as <u>{{ user.username }}!</u></h1>
              <hr>
              <a href="{% url 'registration:logout_user' %}">
                <div class="btn btn-primary">Logout</div>
              </a>
            </div>
          {% else %}
          <!--Display when user not logged-------------------------->
            {% include 'registration/login.html' %}
          {% endif %}
        </div>
      </div>
    </div>
</div>

templates/home/home.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row align-items-center">
    <!--Column 1 - Summary of clicks---------------------------------->
    <div id="col_1" class="col-md-4">
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="col-md-4">
            <h4>Total clicks</h4><br><h3><b>{{ total_clicks }}</b></h3>
          </div>
          <div class="col-md-4">
            <h4>Average clicks</h4><br><h3><b>{{ average_clicks }}</b></h3>
          </div>
          <div class="col-md-4">
            <h4>Latest clicker</h4><br><h3><b>{{ last_clicker }}</b></h3>
          </div>
        </div>
        <hr>
        <div class="row align-items-center">
            <h4>Most clicks</h4><br><h3><b>{{ most_clicker }}</b></h3>
        </div>
      </div>
    </div>
    <!--Column 2-The button------------------------------------------->
    <div id="col_2" class="col-md-4">
      <div>
        {% if user.is_authenticated %}
            <a type="post"
               href="{% url 'home:clicked' %}">
                <img id="custom_button" src="static/images/button.png">
            </a>
        {% else %}
            <img src="static/images/button.png">
        {% endif %}
      </div>
    </div>
    <!--Column 3 - user summary--------------------------------------->
    <div id="col_3" class="col-md-4">
      {% if user.is_authenticated %}
        <div class="row align-items-center">
          <h4>Logged in clicker</h4><br><h3><b>{{ username }}</b></h3>
        </div>
        <hr>
        <div class="container-fluid">
          <div class="row align-items-center">
            <div class="col-md">
              <h4>Total clicks</h4>
              <h1><b>{{ user_clicks }}</b></h1>
            </div>
          </div>
        </div>
      {% else %}
      <br><br><br>
      <h1>Login to get clicking!!!</h1>
      <br><br><br>
      {% endif %}
    </div>

  </div>
</div>
{% endblock %}

templates/polls/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}

<div class="card">
  <div class="card-body">
      <h2 class="card-title">{{question.question_text}}</h2>

      {% if error_message %}
      <p><strong>{{error_message}}</strong></p>
      {% endif %}
      
        <h6 class="card-subtitle mb-2 text-muted">Select your answer below</h6>
        <br>
        <h5 class="card-text">

          <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}

            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice {{
                    forloop.counter
                }}" value="{{ choice.id }}" />
                <label for="choice {{ forloop.counter }}">
                    {{ choice.choice_text }}
                </label>
                <br />
            {% endfor %}
            <br><br>
            <input type="submit" value="Vote" class="card-link"/>
            <a href="/" class="card-link">Back</a>
          </form>
        </h5>
      
  </div>
</div>

{% else %}
<a href = "{% url 'login' %}">LOGIN</a>
{% endif %}

{% endblock %}

templates/polls/polls.html
<!DOCTYPE html>
{% extends 'base.html' %}

<ul>
{% block content %}
  {% if latest_question_list %}
    {% for question in latest_question_list %}
      <div class="card">
        <div class="card-body">
          <li>
            {% if user.is_authenticated %}
            <a href = "{% url 'polls:detail' question.id %}">
                {{ question.question_text }}
            </a>
              {% else %}
              <a href = "{% url 'login' %}">
                {{ question.question_text }}
              </a>
              <b>Log in to vote!</b>
            {% endif %}
          </li>
        </div>
      </div>
    {% endfor %}

    {% else %}
      <p>No polls are available.</p>
  {% endif %}
{% endblock %}
</ul>      

templates/polls/results.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}

<div class="card">
  <div class="card-body">
      <h2 class="card-title">{{question.question_text}}</h2>
      <h6 class="card-subtitle mb-2 text-muted">Select your answer below</h6>
      <br>
      <h5 class="card-text">  
        {% for choice in question.choice_set.all %}
          <li>
            {{ choice.choice_text }} -- {{ choice.votes}}
            vote{{choice.votes|pluralize}}
          </li>
        {% endfor %}
      <br><br>
      <a href="{% url 'polls:detail' question.id %}" class="card-link">Vote again?</a>
      <a href="/" class="card-link">Back</a>
      </h5>
  </div>
</div>

{% else %}
<a href = "{% url 'login' %}">LOGIN</a>
{% endif %}

{% endblock %}